### ISSUE TITLE
解决某些USB不识别

### ISSUE THREAD

**Issue by xuelingkang** [mrdonkey3/hackintosh-oc-msi-b460m-mortar-i7-10700-big-sur#1]
感谢您的开源，对我的帮助很大
我的主板是微星B460M MORTAR WIFI，没有用博通网卡，cpu和您的一样
一开始我的板载蓝牙无法识别到，另外有两个USB2.0接口无法使用，我以为是无解，但是从网上看到很多AX200系列的无限网卡和蓝牙都是可以驱动的
后来我通过阅读OpenCore Install Guide，发现补丁中缺少了SSDT-RHUB.asl导致某些USB不识别，添加这个补丁之后解决了，现在板载无线和蓝牙都能驱动
虽然您的主板不是WIFI版的，但是我猜您可能也有不能识别的USB接口吧，如果您有这样的问题，参考[Fixing USB](https://dortania.github.io/Getting-Started-With-ACPI/Universal/rhub.html)，（我选择的是手动编译方式）
谢谢！

**Comment by mrdonkey3** [comment]
我目前没发现存在这个问题，不过谢谢你分享了你的方案^_^

**Comment by mrdonkey3** [comment]
> 感谢您的开源，对我的帮助很大
> 我的主板是微星B460M MORTAR WIFI，没有用博通网卡，cpu和您的一样
> 一开始我的板载蓝牙无法识别到，另外有两个USB2.0接口无法使用，我以为是无解，但是从网上看到很多AX200系列的无限网卡和蓝牙都是可以驱动的
> 后来我通过阅读OpenCore Install Guide，发现补丁中缺少了SSDT-RHUB.asl导致某些USB不识别，添加这个补丁之后解决了，现在板载无线和蓝牙都能驱动
> 虽然您的主板不是WIFI版的，但是我猜您可能也有不能识别的USB接口吧，如果您有这样的问题，参考[Fixing USB](https://dortania.github.io/Getting-Started-With-ACPI/Universal/rhub.html)，（我选择的是手动编译方式）
> 谢谢！
我目前没发现存在这个问题，不过谢谢你分享了你的方案^_^




> 感谢您的开源，对我的帮助很大
> 我的主板是微星B460M MORTAR WIFI，没有用博通网卡，cpu和您的一样
> 一开始我的板载蓝牙无法识别到，另外有两个USB2.0接口无法使用，我以为是无解，但是从网上看到很多AX200系列的无限网卡和蓝牙都是可以驱动的
> 后来我通过阅读OpenCore Install Guide，发现补丁中缺少了SSDT-RHUB.asl导致某些USB不识别，添加这个补丁之后解决了，现在板载无线和蓝牙都能驱动
> 虽然您的主板不是WIFI版的，但是我猜您可能也有不能识别的USB接口吧，如果您有这样的问题，参考[Fixing USB](https://dortania.github.io/Getting-Started-With-ACPI/Universal/rhub.html)，（我选择的是手动编译方式）
> 谢谢！

我目前没发现存在这个问题，不过谢谢你分享了你的方案^_^

**Comment by mrdonkey3** [comment]
> 感谢您的开源，对我的帮助很大
> 我的主板是微星B460M MORTAR WIFI，没有用博通网卡，cpu和您的一样
> 一开始我的板载蓝牙无法识别到，另外有两个USB2.0接口无法使用，我以为是无解，但是从网上看到很多AX200系列的无限网卡和蓝牙都是可以驱动的
> 后来我通过阅读OpenCore Install Guide，发现补丁中缺少了SSDT-RHUB.asl导致某些USB不识别，添加这个补丁之后解决了，现在板载无线和蓝牙都能驱动
> 虽然您的主板不是WIFI版的，但是我猜您可能也有不能识别的USB接口吧，如果您有这样的问题，参考[Fixing USB](https://dortania.github.io/Getting-Started-With-ACPI/Universal/rhub.html)，（我选择的是手动编译方式）
> 谢谢！

我目前没发现存在这个问题，不过谢谢你分享了你的方案^_^
