### ISSUE TITLE
双显示器有影响吗一个DP一个HDMI

### ISSUE THREAD

**Issue by evan-xie** [mrdonkey3/hackintosh-oc-msi-b460m-mortar-i7-10700-big-sur#2]
双显示器有影响吗一个DP一个HDMI,另外我想把dp转成hdmi线，看你踩了坑有什么推荐的转接线不

**Comment by mrdonkey3** [comment]
目前使用HDMI转HDMI线

山泽(SAMZHE)HDMI线2.0版 4k数字高清线 3D视频线 笔记本电脑连接电视投影仪显示器连接线 黑色1.5米 915HD


之前买的DP转HDMI (我接了会闪屏，原因未知)
毕亚兹 DP转HDMI转接线 1.8米 4K高清连接线 1.2版 DisplayPort转hdmi公对公 电脑电视转换线 XL21

目前只使用HDMI-HDMI线

**Comment by evan-xie** [comment]
所以 “毕亚兹 DP转HDMI转接线 1.8米 4K高清连接线 1.2版 DisplayPort转hdmi公对公 电脑电视转换线 XL21” 这个线是OK的对嘛

**Comment by mrdonkey3** [comment]
> 双显示器有影响吗一个DP一个HDMI,另外我想把dp转成hdmi线，看你踩了坑有什么推荐的转接线不

这个是我用的有问题的线😂

**Comment by mrdonkey3** [comment]
看readme里面有我具体的电脑配置信息
