### ISSUE TITLE
现在还在维护吗

### ISSUE THREAD

**Issue by evan-xie** [mrdonkey3/hackintosh-oc-msi-b460m-mortar-i7-10700-big-sur#3]
前两天看推送了11.3 可以更新不

**Comment by mrdonkey3** [comment]
我升级了11.2，11.3的没升级，不好下结论

**Comment by mrdonkey3** [comment]
> 前两天看推送了11.3 可以更新不

我升级了11.2，11.3的没升级，不好下结论

**Comment by evan-xie** [comment]
对 我开始就装了11.2  一直比较正常的 等过段时间 我找个移动硬盘升级11.3试试 没问题再说

**Comment by mrdonkey3** [comment]
> 对 我开始就装了11.2 一直比较正常的 等过段时间 我找个移动硬盘升级11.3试试 没问题再说

前几天升了11.4，没问题
