### ISSUE TITLE
主板 CPU 蓝牙网卡一样，加了一块 RX550 4G 显卡

### ISSUE THREAD

**Issue by WeiJinglun** [mrdonkey3/hackintosh-oc-msi-b460m-mortar-i7-10700-big-sur#5]
OpenCore0.7.8 macOS 12.2.1
我是从 11.6 升级上来的，之后，用 hackintool 检测，系统 杂项中的蓝牙模块不显示的
但是 随行 隔空投送都是好使的，不知道您遇到这个问题了吗
还有一个是 USB 睡眠唤醒的问题，我看远景大佬说了，板载的 usb2.0 是通过 hub 转出来的，不能设置为内建模式，如果想启用 Usb 唤醒，要把白果网卡的 usb 查到别的 usb 接口上，自己可以调整转接线

**Comment by mrdonkey3** [comment]
> OpenCore0.7.8 macOS 12.2.1 我是从 11.6 升级上来的，之后，用 hackintool 检测，系统 杂项中的蓝牙模块不显示的 但是 随行 隔空投送都是好使的，不知道您遇到这个问题了吗 还有一个是 USB 睡眠唤醒的问题，我看远景大佬说了，板载的 usb2.0 是通过 hub 转出来的，不能设置为内建模式，如果想启用 Usb 唤醒，要把白果网卡的 usb 查到别的 usb 接口上，自己可以调整转接线

这是我的检测，看起来没问题

![hackintool](https://user-images.githubusercontent.com/34863197/158177129-5d22c52d-1632-4401-8251-8d1d9c5a9e93.png)

我的唤醒之前usb2.0也是无效的，这次升级OC0.7.9和更新ACPI/Drivers/Kexts无脑更新一波居然可以了

**Comment by WeiJinglun** [comment]
你现在的系统是 BigSur 11.6 吧，12 之后 mac 的蓝牙的加载方式变了
根据你现在 0.7.9 的情况，晚上我更新一下 0.7.9 试一下，看下 USB 唤醒的问题能否解决

**Comment by mrdonkey3** [comment]
> 你现在的系统是 BigSur 11.6 吧，12 之后 mac 的蓝牙的加载方式变了 根据你现在 0.7.9 的情况，晚上我更新一下 0.7.9 试一下，看下 USB 唤醒的问题能否解决

是的，11.6.4

**Comment by WeiJinglun** [comment]
昨天，跟随 12.3 发布了 11.6.5 的推送，在远景论坛里面，12.3 更新挂了一批显卡，11.6.5 现在还是没啥变动
如果你的机器是工作主力机，还是就用现在的系统就好，等下一个稳定版本，在更新
